site_name: 1kUSD - The Kaspa Stablecoin
site_url: https://neabouli.github.io/1kUSD/
theme:
  name: material
  language: en
  logo: assets/1kUSD.png
  favicon: assets/1kUSD.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - content.tabs.link
    - search.highlight
  palette:
    primary: teal
    accent: lime

extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/Kaspa_USD
    - icon: fontawesome/brands/github
      link: https://github.com/NeaBouli/1kUSD

nav:
  - Home: INDEX.md
  - What is 1kUSD?: what-is-1kusd.md
  - Why 1kUSD?: why-1kusd.md
  - How It Works: how-it-works.md
  - Use Cases: use-cases.md
  - Security: security.md
  - Roadmap: roadmap.md
  - Whitepaper:
      - English: whitepaper/WHITEPAPER_1kUSD_EN.md
      - Deutsch: whitepaper/WHITEPAPER_1kUSD_DE.md
  - Community: community.md
